### PR TITLE
Use inline style for Google fonts

### PR DESCRIPTION
**Pull request by beaufortfrancois**
Instead of having a potentially not needed font, you may want to inline the `<style>`. Does that make sense?

FYI @philippeantoine

### CODE REVIEW

**Comment by MunifTanjim** [comment]
What's the benefit of using inline css here?

**Comment by beaufortfrancois** [comment]
Each time you go to https://minimo.netlify.com/, an HTTP request (https://fonts.googleapis.com/css?family=Ubuntu:400,400i,700&subset=latin) gets issued even though I might not use it.

Instead of seeing this happening, you can simply inline the content of the response.

**Comment by Fastidious** [comment]
I am sorry, but this change is horrible. It adds extra code that isn't needed, and does not fix any problem.

**Comment by beaufortfrancois** [comment]
Go to https://minimo.netlify.com/, open your DevTools, and you'll get bandwidth wasted if you don't need those:
screenshot 2017-12-15 at 3 31 38 pm

I agree this looks ugly but this could be improved by adding comments around it. I wanted to start a discussion more than actually submitting this PR ;)

**Comment by Fastidious** [comment]
@beaufortfrancois I see it. I don't use that font, so I guess it is safe for me to remove that line under my own `/layouts/partials/head/includes.html`.

**Comment by MunifTanjim** [comment]
Oh, I see. Well, I knew about the extra HTTP request. And it was a conscious decision to use the Fonts API. Here are some of my reasons:

- Probably it's unlikely, but what if for some reason the font's link (`https://fonts.gstatic.com/s/ubuntu/v11/4iCu6KVjbNBYlgoKej75l0mwFg.woff2`) changes in the future? Then I'd have to change the inlined CSS manually.

- Minimo is a very lightweight theme. I don't think an extra HTTP request will cause any noticeable performance hit here.

- And if someone really need to optimize this, they can easily override this single template file (`includes.html`) and add inlined Fonts API response, or host their own version of the fonts.

@beaufortfrancois

**Comment by beaufortfrancois** [comment]
If it is a conscious decision, then there it is. I'll override the single template file `includes.html`.
Thanks for the answer!

**Comment by beaufortfrancois** [comment]
Quick newbee question: How would you override this file if I'm simply using git submodule to point to your version? Is there a way from the `config.toml` file to link to my overridden `includes.html`?

**Comment by MunifTanjim** [comment]
- You create a **`/layouts/partials/head/`** folder in your site's root directory.
- Put a file named **`includes.html`** in that directory.

That's all.

Hugo will pick up **`/layouts/partials/head/includes.html`** instead of **`/themes/minimo/layouts/partials/head/includes.html`**

**Comment by beaufortfrancois** [comment]
Thank you! I'm gonna close this.

For info, here's a super talk about Fonts: https://vimeo.com/241111413

**Pull request closed without merging**
