### PR TITLE
Add Polish translation

### PR DESCRIPTION
**Pull request by matrixik**
I'm not sure in what context `[noTerm]` is used. Could you show me example?

Reading time in Polish is different for 1 min (1 minuta),
ending with 2-4 (3 minuty, 24 minuty),
ending with 5-1 (5 minut, 76 minut, 90 minut).
But you don't need to care about that.

Rest should be fine.

### CODE REVIEW

**Comment by MunifTanjim** [comment]
`[noTerm]` is used when there's no `taxonomy` item for a `taxonomyTerm`. For example:

if there is no `tags` item in your site, then the `/tags/` page will show "Not a single tag!"

**Comment by MunifTanjim** [comment]
And about the minuta, minuty & minut - I can't think of a solution at this moment. Hugo doesn't currently provide that much control over the translation strings. But if you can come up with some clever solution, you are welcome to share it.

( one possible solution would be to use front-end JavaScript to manipulate that string :wink: )

**Comment by MunifTanjim** [comment]
@matrixik Let me know when you are done with it.

**Comment by matrixik** [comment]
OK, looks fine now and can be merged. Thank you for nice theme.

**Comment by MunifTanjim** [comment]
thanks for your help :smiley: @matrixik

**Pull request merged**
