### PR TITLE
misspell [translation] en, add [translation] id, enhance [template] permalink /search

### PR DESCRIPTION
**Pull request by djiwan**
### Misspell [translation]: en.toml
on 
```toml
[commentSubmissionErrorMessage]
other = "Error occurred. Couldn't submit your comment. Please try again. Thank You!"
```
**eccured** is misspell, the correct spelling is **occurred**

### Added [translation]: id.toml
Because I use this theme for my blog that supports Indonesian Language, so I made translation for Bahasa Indonesia.

### Enhance [template]: permalink search
After I changed my blog into Indonesian Language, only one hasn't. The permalink when you submit search form.

Permalink before   `/search?q=`
```html
<form action='{{ ( or .Site.Permalinks.search "search" ) | relLangURL }}' id='search-form' class='search-form'>
```
You can set permalink in config.toml
```toml
[permalinks]
page = "/:slug/"
search = "/cari"
```
Permalink after `/cari?q=`

### CODE REVIEW

**Comment by MunifTanjim** [comment]
Hello @djiwan, thanks for the PR. But this PR includes unrelated changes together.
I'd love to have them in separate PRs.

**Comment by djiwan** [comment]
@MunifTanjim , I'm new in github. I don't know yet how things work here.

**Comment by djiwan** [comment]
let me learn a minutes

**Comment by MunifTanjim** [comment]
Oh, that's alright. Are you familiar with `git`?

After you've freshly forked `minimo` from [MunifTanjim/minimo](MunifTanjim/minimo) to your own account on GitHub. You'll need to:

- Clone it on your machine. `git clone https://github.com/djiwan/minimo`
- Create a new branch. `git checkout -b feature/id-translation`
- Add the `/i18n/id.toml` file.
- Commit it. `git add -A && git commit -m "Add translation for Bahasa Indonesia"
- Push it to GitHub. `git push --set-upstream origin feature/id-translation`
- Then you can create a PR on GitHub from your `feature/id-translation` branch to this repo's `master` branch.

Maybe take a look at his article: https://opensource.com/article/19/7/create-pull-request-github
This might help you. You can also Google around a little bit, or ask me if you're confused about anything..

**Pull request closed without merging**
